# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Marine Heatwave Cookbook
author: Chia-Wei Hsu
logo: MHW_maps_demo3.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: MHWbook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/chiaweh2/marine-heatwaves-jupyterbook # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"